# Pull base image.
FROM ubuntu:14.04

# This is a volume data container, holding file assets and db directory.
VOLUME ["/var/lib/mysql", "/var/www/drupal/sites/default/files", "/var/www/drupal/sites/default/private"]

# Do nothing, return successful.
CMD ["true"]
